### ISSUE TITLE
possible memory leak when using FtpClose to close a control connection opened by FtpConnect(nControl)

### ISSUE THREAD

**Issue by tybilgic** [codebrainz/ftplib#3]
https://github.com/codebrainz/ftplib/blob/88b9ac8427b9b5e3d9fd4d0e1f2f9fbebe81bcd8/ftplib.c#L960

FtpQuit frees "nControl -> buf" when closing a control handle but FtpClose doesn't. Is this intentional?

**Comment by codebrainz** [comment]
I have no idea, I just made some build system changes, I am not the author and haven't ever even looked at the code before. You could try the [upstream](http://nbpfaus.net/~pfau/ftplib/), it's been updated since 2010 when I made this repo (and haven't looked at it since). It's entirely possible this leak, if any, would be fixed.
